include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    camel_case_types: ignore
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    non_constant_identifier_names: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    unnecessary_brace_in_string_interps: ignore
    use_key_in_widget_constructors: ignore
